# Generated by Django 4.2.7 on 2026-08-17 09:30

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_supplierledger_gsttransaction_customerledger'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchasebillitem',
            name='cess_amount',
        ),
        migrations.AddField(
            model_name='gsttransaction',
            name='hsn_sac_code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='gsttransaction',
            name='quantity',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AddField(
            model_name='gsttransaction',
            name='uqc_unit',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='invoiceitem',
            name='hsn_sac_code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='purchasebillitem',
            name='hsn_sac_code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='quotationitem',
            name='hsn_sac_code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='salesorderitem',
            name='hsn_sac_code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
