# Generated by Django 4.2.7 on 2026-08-17 12:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0003_remove_purchasebillitem_cess_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hsnsacmaster',
            name='category',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='hsnsacmaster',
            name='cgst_rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='hsnsacmaster',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='hsnsacmaster',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_hsn_codes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='hsnsacmaster',
            name='effective_from',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hsnsacmaster',
            name='effective_to',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hsnsacmaster',
            name='igst_rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='hsnsacmaster',
            name='sgst_rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='hsnsacmaster',
            name='sub_category',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='hsnsacmaster',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='hsnsacmaster',
            name='uqc',
            field=models.CharField(blank=True, default='PCS', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='hsnsacmaster',
            name='code',
            field=models.CharField(max_length=20),
        ),
    ]
