# Generated by Django 4.2.7 on 2026-08-18 11:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0005_customuser_profile_photo_customuser_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='signature',
            field=models.ImageField(blank=True, null=True, upload_to='company_signatures/'),
        ),
        migrations.AddField(
            model_name='company',
            name='stamp',
            field=models.ImageField(blank=True, null=True, upload_to='company_stamps/'),
        ),
        migrations.CreateModel(
            name='PasswordResetOTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('otp_hash', models.CharField(max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('attempts', models.IntegerField(default=0)),
                ('is_verified', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='otps', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
