# Generated by Django 4.2.7 on 2026-08-19 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0006_company_signature_company_stamp_passwordresetotp'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hsnsacmaster',
            options={'verbose_name': 'HSN/SAC Master', 'verbose_name_plural': 'HSN/SAC Masters'},
        ),
        migrations.AddConstraint(
            model_name='hsnsacmaster',
            constraint=models.UniqueConstraint(condition=models.Q(('company__isnull', True)), fields=('type', 'code'), name='unique_system_hsn_sac_code'),
        ),
        migrations.AddConstraint(
            model_name='hsnsacmaster',
            constraint=models.UniqueConstraint(condition=models.Q(('company__isnull', False)), fields=('company', 'type', 'code'), name='unique_company_hsn_sac_code'),
        ),
    ]
