# Generated by Django 4.2.7 on 2026-08-24 08:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0007_alter_hsnsacmaster_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotation',
            name='converted_to_sales_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_quotations', to='billing.salesorder'),
        ),
    ]
