# Generated by Django 4.2.7 on 2026-08-25 06:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0010_purchaseorder_supplier_address_snapshot_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorderitem',
            name='item_image',
            field=models.ImageField(blank=True, null=True, upload_to='purchase_order_item_photos/'),
        ),
        migrations.AlterField(
            model_name='purchaseorderitem',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='billing.product'),
        ),
    ]
