# Generated by Django 4.2.7 on 2026-08-25 09:19

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0012_tax_invoice_payment_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuotationPredefinedTerm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term_text', models.TextField()),
                ('display_order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='billing.company')),
            ],
            options={
                'ordering': ['display_order', 'id'],
            },
        ),
        migrations.AddField(
            model_name='quotation',
            name='cess_total',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15),
        ),
        migrations.AddField(
            model_name='quotation',
            name='discount_total',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15),
        ),
        migrations.AddField(
            model_name='quotation',
            name='payment_terms',
            field=models.CharField(blank=True, default='As specified in proposal', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='quotation',
            name='round_off',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15),
        ),
        migrations.CreateModel(
            name='QuotationSelectedTerm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term_text', models.TextField()),
                ('display_order', models.IntegerField(default=0)),
                ('is_custom', models.BooleanField(default=False)),
                ('predefined_term', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='billing.quotationpredefinedterm')),
                ('quotation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='selected_terms', to='billing.quotation')),
            ],
            options={
                'ordering': ['display_order', 'id'],
            },
        ),
    ]
