# Generated by Django 5.2 on 2026-09-04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0015_gstapplication'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hsnsacmaster',
            name='gst_rate',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=5, null=True),
        ),
    ]
