# Generated by Django 4.2.30 on 2026-09-04 11:40

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0016_hsnsacmaster_gst_rate_optional'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hsnsacmaster',
            name='gst_rate',
            field=models.DecimalField(decimal_places=2, default=Decimal('18.00'), max_digits=5),
        ),
    ]
