# Generated by Django 4.2.7 on 2026-09-04 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0017_alter_hsnsacmaster_gst_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='other_website',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='website',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
